### PR TITLE
Added userspace code to allow use of new syscalls

### PR DESCRIPTION
**Pull request by geoffret**
This is just the associated patch to go with the litmus-rt patch. 
- budget_exhausted(int*): Sets the flag if the budget for the current job has been exhausted
- get_slack(lt_t*): Gets the remaining time until the deadline for the current job is reached

### CODE REVIEW

**Comment by GElliott** [comment]
> On Sep 4, 2015, at 1:48 PM, geoffret notifications@github.com wrote:
> 
> This is just the associated patch to go with the litmus-rt patch.
> 
> budget_exhausted(int_): Sets the flag if the budget for the current job has been exhausted
> get_slack(lt_t_): Gets the remaining time until the deadline for the current job is reached
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/LITMUS-RT/liblitmus/pull/1
> 
> Commit Summary
> 
> Added userspace code to allow use of new syscalls
> File Changes
> 
> M include/litmus.h (13)
> M src/syscalls.c (10)
> Patch Links:
> 
> https://github.com/LITMUS-RT/liblitmus/pull/1.patch
> https://github.com/LITMUS-RT/liblitmus/pull/1.diff
> —
> Reply to this email directly or view it on GitHub.

Maybe this would be something better done through the control page?  The page could export the job deadline.  Userspace could call clock_gettime() and use the exported deadline to compute slack.  A flag indicating budget exhaustion could also be put in the control page.

-Glenn

**Comment by geoffret** [comment]
Hi Glenn,

I looked into what the control pages are in this project and agree that they may
be a better idea. However, I do not think I'll be able to get back to this for a
while.  

When more time becomes available, I'll go in and reimplement these using
the control pages. 

Thanks,
Geoffrey

**Comment by brandenburg** [comment]
Geoffrey, thanks a lot for the patch! I think this would be good functionality to have. Unfortunately, I think the kernel implementation doesn't work correctly. I'll add a comment over there in the diff to explain why. I have an old patch for similar functionality from my RTSS'14 MC-IPC work. Let me propose an alternate implementation later today.

**Comment by brandenburg** [comment]
Please have a look at the branches named "prop/get-budget".
- https://github.com/LITMUS-RT/litmus-rt/commits/prop/get-budget
- https://github.com/LITMUS-RT/liblitmus/commits/prop/get-budget

**Comment by geoffret** [comment]
Updated the interface to use control pages, as recommended above. 

Closing as request comes from a different branch.

**Pull request closed without merging**
